# Generated by Django 4.2.7 on 2025-10-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="analysisproject",
            unique_together={("name", "user")},
        ),
    ]
