# Generated by Django 4.2.7 on 2025-10-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_analysisproject_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysisproject",
            options={"ordering": ["-updated_at"]},
        ),
    ]
