# Generated by Django 4.2.7 on 2025-09-19 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("ndvi", "NDVI Analysis"),
                            ("lst", "Land Surface Temperature"),
                            ("sentinel1", "Sentinel-1 SAR"),
                            ("sentinel2", "Sentinel-2 NDVI"),
                            ("comprehensive", "Comprehensive Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "satellite",
                    models.CharField(
                        choices=[("landsat", "Landsat"), ("sentinel", "Sentinel")],
                        default="landsat",
                        max_length=20,
                    ),
                ),
                ("geometry_data", models.JSONField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cloud_cover", models.IntegerField(default=20)),
                ("use_cloud_masking", models.BooleanField(default=True)),
                ("strict_masking", models.BooleanField(default=False)),
                ("selected_images", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="core.analysisproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=255)),
                ("total_images", models.IntegerField()),
                ("images_used", models.IntegerField()),
                ("date_range", models.CharField(max_length=100)),
                ("cloud_cover_range", models.CharField(blank=True, max_length=100)),
                ("image_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_collections",
                        to="analysis.analysisrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("statistics", models.JSONField(blank=True, null=True)),
                (
                    "plot_file",
                    models.FileField(
                        blank=True, null=True, upload_to="results/plots/%Y/%m/%d/"
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        blank=True, null=True, upload_to="results/csv/%Y/%m/%d/"
                    ),
                ),
                (
                    "map_file",
                    models.FileField(
                        blank=True, null=True, upload_to="results/maps/%Y/%m/%d/"
                    ),
                ),
                ("total_observations", models.IntegerField(default=0)),
                ("date_range_covered", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="analysis.analysisrequest",
                    ),
                ),
            ],
        ),
    ]
