# Generated by Django 4.2.7 on 2025-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_alter_analysisrequest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="polarization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VV", "VV Polarization"),
                    ("VH", "VH Polarization"),
                    ("both", "Both VV and VH"),
                ],
                default="VV",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="analysisrequest",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("ndvi", "NDVI Analysis"),
                    ("lst", "Land Surface Temperature"),
                    ("backscatter", "SAR Backscatter Analysis"),
                    ("sentinel1", "Sentinel-1 SAR"),
                    ("sentinel2", "Sentinel-2 NDVI"),
                    ("comprehensive", "Comprehensive Analysis"),
                ],
                max_length=20,
            ),
        ),
    ]
