name: Earth_Observation_CI

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  backend-lint:
    name: Backend Lint & Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 autopep8

      - name: Run flake8 linting
        working-directory: ./backend
        run: |
          # Run flake8 on core application directories
          flake8 apps/ geoanalysis/ --count --show-source --statistics
          echo "Flake8 linting completed successfully"

      - name: Check code formatting
        working-directory: ./backend
        run: |
          autopep8 --diff --recursive apps/ geoanalysis/
          echo "Code formatting check completed"

  backend-security:
    name: Backend Security Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install security tools
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety

      - name: Bandit security scan
        working-directory: ./backend
        run: |
          # Run bandit with custom configuration
          bandit -r apps/ geoanalysis/ -c .bandit
          echo "Bandit security scan completed successfully"

      - name: Safety vulnerability check
        working-directory: ./backend
        run: |
          safety check --json || echo "⚠️ Safety check completed with warnings"
        continue-on-error: true

  backend-tests:
    name: API Tests
    runs-on: ubuntu-latest
    needs: [backend-lint, backend-security]

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY || 'django-insecure-ci-test-key-only' }}
      DJANGO_SETTINGS_MODULE: geoanalysis.test_settings

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        working-directory: ./backend
        run: |
          python manage.py test
          echo "API tests completed"
          
